'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class Updates
    
    Private buildField As UpdatesBuild
    
    Private versionField As String
    
    Private dateField As String
    
    '''<remarks/>
    Public Property Build() As UpdatesBuild
        Get
            Return Me.buildField
        End Get
        Set
            Me.buildField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [Date]() As String
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class UpdatesBuild
    
    Private changesField() As Object
    
    Private featuresField() As Object
    
    Private revisionsField() As Object
    
    Private bugFixesField() As Object
    
    Private versionField As String
    
    Private releasedField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Change", IsNullable:=false)>  _
    Public Property Changes() As Object()
        Get
            Return Me.changesField
        End Get
        Set
            Me.changesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Feature", IsNullable:=false)>  _
    Public Property Features() As Object()
        Get
            Return Me.featuresField
        End Get
        Set
            Me.featuresField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Revision", IsNullable:=false)>  _
    Public Property Revisions() As Object()
        Get
            Return Me.revisionsField
        End Get
        Set
            Me.revisionsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("BugFix", IsNullable:=false)>  _
    Public Property BugFixes() As Object()
        Get
            Return Me.bugFixesField
        End Get
        Set
            Me.bugFixesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property released() As String
        Get
            Return Me.releasedField
        End Get
        Set
            Me.releasedField = value
        End Set
    End Property
End Class
